import { join } from "node:path";
import type { InitOptions } from "../../../core/src/contracts.js";
import { ensureDir, writeTextFile } from "../../../core/src/fs.js";

export interface AdapterResult {
  written: string[];
  skipped: string[];
}

export async function generateCodexAdapter(options: InitOptions): Promise<AdapterResult> {
  const written: string[] = [];
  const skipped: string[] = [];
  const dirs = [
    ".codex/agents",
    ".codex/skills",
    ".codex/commands",
  ];

  for (const dir of dirs) {
    await ensureDir(join(options.root, dir));
  }

  await write(join(options.root, ".codex/agents/README.md"), agentsReadme(), options.force, written, skipped);
  await write(join(options.root, ".codex/agents/openworkflow-orchestrator.md"), orchestratorAgent(), options.force, written, skipped);

  const commands = [
    ["build-workflow.md", buildWorkflowCommand()],
    ["build-vision.md", commandDoc("build-vision", "Use one-question-at-a-time collaboration to create or refine `.openworkflow/vision/VISION_CONTRACT.yaml`.")],
    ["build-validation.md", commandDoc("build-validation", "Read vision artifacts and create validation-first prioritization under `.openworkflow/validation/`.")],
    ["build-prototype.md", commandDoc("build-prototype", "Read validation artifacts and create a focused local prototype under `.openworkflow/prototypes/`.")],
    ["build-decision.md", commandDoc("build-decision", "Record user review outcomes from prototype or production slices under `.openworkflow/decisions/`.")],
    ["build-spec.md", commandDoc("build-spec", "Create one focused production spec from an accepted prototype decision.")],
    ["build-change.md", commandDoc("build-change", "Create one focused production change from a spec for the current core feature.")],
    ["run-team.md", commandDoc("run-team", "Execute approved production runtime work after spec and change contracts exist.")],
  ];
  for (const [name, content] of commands) {
    await write(join(options.root, ".codex/commands", name), content, options.force, written, skipped);
  }

  await write(join(options.root, ".codex/skills/openworkflow.md"), codexSkill(), options.force, written, skipped);

  return { written, skipped };
}

async function write(path: string, content: string, force: boolean, written: string[], skipped: string[]): Promise<void> {
  const action = await writeTextFile(path, content, force);
  if (action === "write") {
    written.push(path);
  } else {
    skipped.push(path);
  }
}

function agentsReadme(): string {
  return `# Codex Agents for OpenWorkflow\n\nThis folder is generated by the OpenWorkflow Codex adapter. The canonical workflow state lives in \`.openworkflow/\`.\n`;
}

function orchestratorAgent(): string {
  return `---\nname: openworkflow-orchestrator\ndescription: Coordinates OpenWorkflow contract stages while keeping .openworkflow as source of truth.\n---\n\n# OpenWorkflow Orchestrator\n\nRead \`.openworkflow/workflow/WORKFLOW_INDEX.yaml\` first. Do not treat \`.codex/\` as the source of truth; it is an adapter layer.\n\nDefault journey:\n\n\`\`\`txt\nvision -> validation -> prototype -> decision -> spec -> change -> runtime\n\`\`\`\n\nPrototype discovery must not create production specs, changes, teams, or runtime state before a decision authorizes continuation.\n`;
}

function buildWorkflowCommand(): string {
  return `# /build-workflow\n\nInitialize or reconcile OpenWorkflow contracts. Use \`.openworkflow/\` as the platform-independent source of truth and \`.codex/\` only as this tool adapter.\n\nRecommended CLI:\n\n\`\`\`bash\nopenworkflow init . --tools codex\nopenworkflow validate --root .\n\`\`\`\n`;
}

function commandDoc(name: string, purpose: string): string {
  return `# /${name}\n\n${purpose}\n\nSource of truth: \`.openworkflow/\`.\n\nKeep artifacts short, scoped, and traceable through \`.openworkflow/workflow/CONTRACT_GRAPH.yaml\`.\n`;
}

function codexSkill(): string {
  return `# OpenWorkflow Codex Adapter\n\nUse this adapter to operate OpenWorkflow from Codex. The durable workflow contracts live in \`.openworkflow/\`.\n\nRules:\n\n- Do not create production specs before validation and prototype decision.\n- Do not create Agent Team runtime before a focused change exists.\n- Keep \`.codex/\` generated or tool-facing; keep product truth in \`.openworkflow/\`.\n`;
}

