import type { CodexTemplate } from "./templates.js";

export function generateAgentTemplates(): CodexTemplate[] {
  return [
    {
      id: "codex.agent.readme",
      path: ".codex/agents/README.md",
      content: agentsReadme(),
    },
    {
      id: "codex.agent.openworkflow-orchestrator",
      path: ".codex/agents/openworkflow-orchestrator.md",
      content: orchestratorAgent(),
    },
  ];
}

function agentsReadme(): string {
  return `# Codex Agents for OpenWorkflow

This folder is generated by the OpenWorkflow Codex adapter. The canonical workflow state lives in \`.openworkflow/\`.
`;
}

function orchestratorAgent(): string {
  return `---
name: openworkflow-orchestrator
description: Coordinates OpenWorkflow contract stages while keeping .openworkflow as source of truth.
---

# OpenWorkflow Orchestrator

Read \`.openworkflow/workflow/WORKFLOW_INDEX.yaml\` first. Do not treat \`.codex/\` as the source of truth; it is an adapter layer.

Default journey:

\`\`\`txt
vision -> validation -> prototype -> decision -> spec -> change -> runtime
\`\`\`

Prototype discovery must not create production specs, changes, teams, or runtime state before a decision authorizes continuation.
`;
}
