export const CODEX_ADAPTER_VERSION = "0.1.0";

export interface CodexTemplate {
  id: string;
  path: string;
  content: string;
}

export function getCodexTemplates(): CodexTemplate[] {
  return [
    {
      id: "codex.agent.readme",
      path: ".codex/agents/README.md",
      content: agentsReadme(),
    },
    {
      id: "codex.agent.openworkflow-orchestrator",
      path: ".codex/agents/openworkflow-orchestrator.md",
      content: orchestratorAgent(),
    },
    {
      id: "codex.command.build-workflow",
      path: ".codex/commands/build-workflow.md",
      content: buildWorkflowCommand(),
    },
    ...commandTemplates(),
    {
      id: "codex.skill.openworkflow",
      path: ".codex/skills/openworkflow.md",
      content: codexSkill(),
    },
  ];
}

function commandTemplates(): CodexTemplate[] {
  const commands = [
    ["build-vision", "Use one-question-at-a-time collaboration to create or refine `.openworkflow/vision/VISION_CONTRACT.yaml`."],
    ["build-validation", "Read vision artifacts and create validation-first prioritization under `.openworkflow/validation/`."],
    ["build-prototype", "Read validation artifacts and create a focused local prototype under `.openworkflow/prototypes/`."],
    ["build-decision", "Record user review outcomes from prototype or production slices under `.openworkflow/decisions/`."],
    ["build-spec", "Create one focused production spec from an accepted prototype decision."],
    ["build-change", "Create one focused production change from a spec for the current core feature."],
    ["run-team", "Execute approved production runtime work after spec and change contracts exist."],
  ] as const;

  return commands.map(([name, purpose]) => ({
    id: `codex.command.${name}`,
    path: `.codex/commands/${name}.md`,
    content: commandDoc(name, purpose),
  }));
}

function agentsReadme(): string {
  return `# Codex Agents for OpenWorkflow

This folder is generated by the OpenWorkflow Codex adapter. The canonical workflow state lives in \`.openworkflow/\`.
`;
}

function orchestratorAgent(): string {
  return `---
name: openworkflow-orchestrator
description: Coordinates OpenWorkflow contract stages while keeping .openworkflow as source of truth.
---

# OpenWorkflow Orchestrator

Read \`.openworkflow/workflow/WORKFLOW_INDEX.yaml\` first. Do not treat \`.codex/\` as the source of truth; it is an adapter layer.

Default journey:

\`\`\`txt
vision -> validation -> prototype -> decision -> spec -> change -> runtime
\`\`\`

Prototype discovery must not create production specs, changes, teams, or runtime state before a decision authorizes continuation.
`;
}

function buildWorkflowCommand(): string {
  return `# /build-workflow

Initialize or reconcile OpenWorkflow contracts. Use \`.openworkflow/\` as the platform-independent source of truth and \`.codex/\` only as this tool adapter.

Recommended CLI:

\`\`\`bash
openworkflow init . --tools codex
openworkflow sync --tools codex
openworkflow validate --root .
\`\`\`
`;
}

function commandDoc(name: string, purpose: string): string {
  return `# /${name}

${purpose}

Source of truth: \`.openworkflow/\`.

Load only the contract files required for this stage. Keep artifacts short, scoped, and traceable through \`.openworkflow/workflow/CONTRACT_GRAPH.yaml\`.
`;
}

function codexSkill(): string {
  return `# OpenWorkflow Codex Adapter

Use this adapter to operate OpenWorkflow from Codex. The durable workflow contracts live in \`.openworkflow/\`.

Rules:

- Do not create production specs before validation and prototype decision.
- Do not create Agent Team runtime before a focused change exists.
- Keep \`.codex/\` generated or tool-facing; keep product truth in \`.openworkflow/\`.
- Run \`openworkflow sync --tools codex\` after upgrading the npm package or changing adapter templates.
`;
}
